version: "3"

services:

  redis:
    image: redis:alpine
    networks:
      - back-tier

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - my-data:/var/lib/postgresql/data
    networks:
      - back-tier

  votee:
    image: dockersamples/examplevotingapp_vote
    ports:
      - 5000:80
    depends_on:
      - redis
    restart: always
    networks:
      - front-tier
      - back-tier

    
  workerr:
    image: dockersamples/examplevotingapp_worker
    restart: always
    networks:
      - back-tier
    
  resultt:
    image: dockersamples/examplevotingapp_result
    ports:
      - 5001:80
    depends_on:
      - db
    restart: always 
    
    networks:
      - front-tier
      - back-tier

volumes:
  my-data: 
    driver: local 
networks:
  front-tier:
  back-tier: