apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
    name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      name: db
      labels:
        app: db
    spec:
      containers:
      - image: postgres:15-alpine
        name: db
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
          name: db
        resources:
          requests:
            cpu: "100m"          # Request 500 millicores of CPU
            memory: "128Mi"      # Request 512 MiB of memory
          limits:
            cpu: "100m"             # Limit CPU to 1 core
            memory: "128Mi"        # Limit memory to 1 GiB
          

---


apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
    name: db
spec:
  type: ClusterIP
  ports:
  - name: db
    port: 5432
    targetPort: 5432
  selector:
    app: db
  
