apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels:
    app: result
    name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      name: result
      labels:
        app: result
    spec:
      containers:
        - image: vishnu9/examplevotingapp_result:1.0
          name: result
          ports:
            - containerPort: 80
              name: result
          resources:
            requests:
              cpu: "100m"          # Request 500 millicores of CPU
              memory: "128Mi"      # Request 512 MiB of memory
            limits:
              cpu: "100m"             # Limit CPU to 1 core
              memory: "128Mi"  
---

apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
    name: result
spec:
  type: LoadBalancer
  ports:
  - name: result
    port: 5001
    targetPort: 80
    protocol: TCP
  selector:
    app: result
