apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: vote
    name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      name: vote
      labels:
        app: vote
    spec:
      containers:
      - image: dockersamples/examplevotingapp_vote
        name: vote
        ports:
        - containerPort: 80
          name: vote
          
---

apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
    name: vote
spec:
  type: LoadBalancer
  ports:
  - name: vote
    port: 5000
    targetPort: 80
    protocol: TCP
  selector:
    app: vote
  
