name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        run: |
           echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Compose Images
        run: |
          docker-compose -f docker-compose.yaml build

      - name: Push Docker Compose Images to Docker Hub
        run: |
          docker-compose -f docker-compose.yaml push

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCP_CREDENTIALS }}
 
      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
 
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        run: |
          gcloud container clusters get-credentials cluster-sample --zone us-central1-c --project ${{ secrets.GCP_PROJECT_ID }}
          kubectl apply -f postgres.yaml --validate=false
          kubectl apply -f redis.yaml --validate=false
          kubectl apply -f result-deployment.yaml --validate=false
          kubectl apply -f vote-deployment.yaml --validate=false
          kubectl apply -f worker.yaml --validate=false
          kubectl get services
